### ISSUE TITLE
Some files loss

### ISSUE THREAD

**Issue by zltshadow** [iwuqing/Polyner#1]
Polyner model(like network sturctures, train details) and  utils not provide, can you provide it?
When run main.py, I found that "AttributeError: module 'Polyner' has no attribute 'train'".

**Comment by iwuqing** [comment]
I have updated related files. Please clone the latest repository and try to run it.

**Comment by zltshadow** [comment]
![image](https://github.com/iwuqing/Polyner/assets/24472735/4845760e-8f19-43a2-800c-ad594cb895f5)
Can you offer your python source code, not the pyc file? Thanks a lot~

**Comment by iwuqing** [comment]
We are considering productizing this work, so we are sorry that we cannot release the source code currently. I think the error "bad magic number ..." could caused by Python's version. The version I used is 3.8.13. May you try to use this version for running it.

**Comment by zltshadow** [comment]
Thank you for your advice; it works for me when I change the Python version. It would be appreciated if you could follow up with open-source code, and I look forward to the day you open-source it.
