### ISSUE TITLE
How to get mask for real world data?

### ISSUE THREAD

**Issue by Golden-Pigeon** [iwuqing/Polyner#5]
Hi authors, thanks for your great work! 

When I reproduce your paper, I wonder how do you get the metal binary mask for real world like the walnut? For synthetic data, since the data is generated based on metal objects with known locations, the locations of the metal objects can be known naturally. But for real world data, we do not know the locations of the metal objects in advance. Do you obtain the location of metal objects in some other ways?

Hope to get your reply!

<img width="843" alt="image" src="https://github.com/user-attachments/assets/53058261-796a-464c-95c9-83bee738b00b">

**Comment by iwuqing** [comment]
Thank you for your interest in our work!

The linear attenuation coefficients (LACs) of metals are typically much higher than those of human tissues. For real-world data, we used a simple binary threshold segmentation on the CT images reconstructed by FBP or FDK algorithms to obtain the metal masks.

**Comment by Golden-Pigeon** [comment]
Thank you for your reply! I'll try it.

Wish you all good!
